kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kubeapp-production1
spec:
  replicas: 3
  template:
    metadata:
      name: kubeapp1
      labels:
        app: kubeapp1
        env: production
    spec:
      containers:
      - name: kubeapp1
        image: app2:1
        imagePullPolicy: Never
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        command: ["/app"]
        ports:
        - name: kubeapp1
          containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: kubeapp-production-service1
  labels:
    app: kubeapp1
    env: production
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: kubeapp1
    env: production
